text:
  name: "Game"
  prefix: "[Game] "
  permission: "game"
  primary-color: "6"
  secondary-color: "e"
  error-color: "c"
size:
  min: 2
  max: 12
arena:
  block-break: false
  item-manage: false
  hunger: false
  fire-block-damage: false
  explosion-block-damage: false
modes:
  game-mode: "ADVENTURE"
  exit-mode: "SURVIVAL"
time:
  game-time: 600
  countdown-time: 60
eco:
  winning-eco: 1000
other:
  join-teleport: true